name: Generate README with Image List

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Generate README.md
      run: |
        echo "| File Name   | Image |" > README.md
        echo "|-------------|-------|" >> README.md
        for file in *.{png,jpg,jpeg}; do
          filename=$(basename "$file")
          echo "| $filename | ![$filename](https://github.com/${{ github.repository }}/raw/main/$file) |" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Automated update to README with image links"
        git push
